### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by 9H1LO** [karpach/remote-shutdown-pc#6]
don't know if i'm doing something wrong, but it gives an exception error when trying to run, maybe some missing dependency ? your other remote shudown app works fine..

I even tried putting the files in the path specified in the error log: C:\projects\remote-controller

error log below:

2020-04-30 09:03:08.5664|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) ---> System.ComponentModel.Composition.CompositionContractMismatchException: Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 38
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 32
2020-04-30 09:03:18.5675|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) ---> System.ComponentModel.Composition.CompositionContractMismatchException: Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 38
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 32
2020-04-30 09:13:38.4157|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) ---> System.ComponentModel.Composition.CompositionContractMismatchException: Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 38
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 32

**Comment by karpach** [comment]
Please try again with a latest changes using VS 2022.
